Fix lens reader arrows direction
samaSiriwardhanage/playlist-label pull request #1
Opened 2022-07-21 03:55 UTC by samaSiriwardhanage

Resolves #104 Lens reader arrows not pointing in the right direction.

### Acceptance Criteria
- [ ]  Update playlist label balena configuration to fix the arrow direction
- [ ] Update the code to allow the configuration to update the arrow direction

### Relevant design files
* None

### Testing instructions
1. None

2022-07-21 08:00 UTC, sighmon requested changes
Looking good so far! Setting the `COLLECT_POSITION` to `right` and unsetting it works for me. But when I try and set it to `left` it still points down.

2022-07-21 08:00 UTC, sighmon commented on app/static/playlist.style.css
> +}
```suggestion

@-webkit-keyframes animatedown {
  0% { -webkit-transform: translateY(0); }
  100% { -webkit-transform: translateY(0.2em); }
}
```

2022-07-24 23:11 UTC, samaSiriwardhanage commented on app/static/playlist.style.css
> +}
Changed code as suggested. Removed spaces.

2022-07-26 02:40 UTC, sighmon requested changes
Looks great! Thanks for fixing that `left` bug.

One small improvement might be to avoid having to duplicate a lot of the code in your new `.collect.left::before` style. So you could do something like this:

```css
.collect:before, .collect.left:before {
  width: 30px;
  height: 41px;
  display: inline-block;
  background: url('down.svg') center/contain no-repeat;
  content: " ";
  margin-right: 10px;
  transition: opacity 500ms;
  transform: rotate(90deg);
  vertical-align: -12px;
  -webkit-animation: animatedown 0.6s infinite alternate ease-in-out;
}

.collect.left:before {
  transform: rotate(-90deg);
  -webkit-animation: animateleft 0.6s infinite alternate ease-in-out;
}
```

2022-07-26 05:44 UTC, sighmon approved these changes
Looks great! I think this is ready to merge to `main`.

2022-07-26 05:49 UTC, merged